/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Controller.DashboardController;
import Controller.MyObjectController;
import Controller.ZoneDessinController;
import java.util.*;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import miaproject.database;

/**
 *
 * @author KADAFI Ben
 */
public class Dashboard extends javax.swing.JFrame {
    
    
    private Connection connect;
    
    private PreparedStatement prepare;
    
    private Statement statement;
    
    private ResultSet result;
    
    Graphics g;
    
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        
        initComponents();
                
        displayUsername();
        
        ZonneDessinContrainte jPanelZoneDessin = new ZonneDessinContrainte();
        DashboardController dash = new DashboardController(jPanelZoneDessin, 
                jButtonValiderTerrain ,rectangleD, ligneD, cercleD, gaumeD,
                noireCou, blancCou, rougeCou, bleueCou, verteCou, jauneCou,
                orangeCou, roseCou, jButtonEffacerTout);
        jPanelZoneDessin.addMouseListener(new ZoneDessinController(dash));
        ajouterMonZoneDessinContrainte(jPanelZoneDessin);
        dash.start();
        
        //Les formes
        sourisD.setSelected(true);
        texteD.setSelected(false);
        ligneD.setSelected(false);
        rectangleD.setSelected(false);
        cercleD.setSelected(false);
        gaumeD.setSelected(false);
        
        //Les painsceuax
        styloPain.setSelected(true);
        stylo1Pain.setSelected(false);
        stylo2Pain.setSelected(false);
        
        //Les couleurs
        noireCou.setSelected(true);
        blancCou.setSelected(false);
        rougeCou.setSelected(false);
        bleueCou.setSelected(false);
        verteCou.setSelected(false);
        jauneCou.setSelected(false);
        orangeCou.setSelected(false);
        roseCou.setSelected(false);
        
        jButtonEffacerTout.setSelected(false);
        
    
    }
    
    public void ajouterMonZoneDessinContrainte(ZonneDessinContrainte jPanelZoneDessin){

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanelZoneDessin);
        jPanelZoneDessin.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(500, 1000, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(100, 480, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelZoneDessin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 1000, 480));
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ouvrir = new javax.swing.JLabel();
        nouveau = new javax.swing.JLabel();
        enregistrer = new javax.swing.JLabel();
        enregistrerSous = new javax.swing.JLabel();
        jLabelNomUtilisateur = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        dashboardLogoutBtn = new javax.swing.JLabel();
        sectionTerain = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTextFieldNomTerrain = new javax.swing.JTextField();
        jButtonValiderTerrain = new javax.swing.JButton();
        jSpinnerLargeurTerrain = new javax.swing.JSpinner();
        jSpinnerHauteurTerrain = new javax.swing.JSpinner();
        jSpinnerHauteurTerrain1 = new javax.swing.JSpinner();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jSpinnerLargeurTerrain1 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        sectionMaison = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jButtonValiderMaison = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jTextFieldNomMaison = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jSpinnerHautMaison = new javax.swing.JSpinner();
        jSpinnerBasMaison = new javax.swing.JSpinner();
        jSpinnerNbrDeChambreMaison = new javax.swing.JSpinner();
        jSpinnerGaucheMaison = new javax.swing.JSpinner();
        jSpinnerDroiteMaison = new javax.swing.JSpinner();
        jSpinnerHauteurMaison = new javax.swing.JSpinner();
        jSpinnerLargeurMaison = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        sourisD = new javax.swing.JToggleButton();
        texteD = new javax.swing.JToggleButton();
        gaumeD = new javax.swing.JToggleButton();
        rectangleD = new javax.swing.JToggleButton();
        cercleD = new javax.swing.JToggleButton();
        ligneD = new javax.swing.JToggleButton();
        jToolBar3 = new javax.swing.JToolBar();
        styloPain = new javax.swing.JToggleButton();
        stylo1Pain = new javax.swing.JToggleButton();
        stylo2Pain = new javax.swing.JToggleButton();
        jToolBar4 = new javax.swing.JToolBar();
        noireCou = new javax.swing.JToggleButton();
        blancCou = new javax.swing.JToggleButton();
        rougeCou = new javax.swing.JToggleButton();
        bleueCou = new javax.swing.JToggleButton();
        verteCou = new javax.swing.JToggleButton();
        jauneCou = new javax.swing.JToggleButton();
        orangeCou = new javax.swing.JToggleButton();
        roseCou = new javax.swing.JToggleButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButtonEffacerTout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user (2).png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 50, 50));

        ouvrir.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        ouvrir.setForeground(new java.awt.Color(255, 255, 255));
        ouvrir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ouvrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/folder_1.png"))); // NOI18N
        ouvrir.setText("Ouvrir");
        ouvrir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ouvrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 100, 50));

        nouveau.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        nouveau.setForeground(new java.awt.Color(255, 255, 255));
        nouveau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nouveau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/new-document.png"))); // NOI18N
        nouveau.setText("Nouveau");
        nouveau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(nouveau, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 100, 50));

        enregistrer.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        enregistrer.setForeground(new java.awt.Color(255, 255, 255));
        enregistrer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enregistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/diskette (1).png"))); // NOI18N
        enregistrer.setText("Enregistrer");
        enregistrer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enregistrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enregistrerMouseClicked(evt);
            }
        });
        jPanel1.add(enregistrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 100, 50));

        enregistrerSous.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        enregistrerSous.setForeground(new java.awt.Color(255, 255, 255));
        enregistrerSous.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enregistrerSous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/save.png"))); // NOI18N
        enregistrerSous.setText("Enregistrer sous");
        enregistrerSous.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(enregistrerSous, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 150, 50));

        jLabelNomUtilisateur.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabelNomUtilisateur.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomUtilisateur.setText("User name");
        jPanel1.add(jLabelNomUtilisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 140, 50));

        jToolBar2.setBackground(new java.awt.Color(102, 102, 102));
        jToolBar2.setRollover(true);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/arrow-left.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton2);

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/right-arrow (1).png"))); // NOI18N
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton4);

        jPanel1.add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 50));

        jPanel2.setBackground(new java.awt.Color(136, 157, 236));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardLogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        dashboardLogoutBtn.setText(" Déconnexion");
        dashboardLogoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardLogoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardLogoutBtnMouseClicked(evt);
            }
        });
        jPanel2.add(dashboardLogoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 110, 30));

        sectionTerain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Largeur(x1):");
        sectionTerain.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 90, 20));

        jLabel37.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText(" Hauteur(y1):");
        sectionTerain.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 90, 20));

        jLabel41.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel41.setText("Nom du terrain:");
        sectionTerain.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 20));

        jTextFieldNomTerrain.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextFieldNomTerrain.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldNomTerrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomTerrainActionPerformed(evt);
            }
        });
        sectionTerain.add(jTextFieldNomTerrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 260, 30));

        jButtonValiderTerrain.setBackground(new java.awt.Color(8, 126, 245));
        jButtonValiderTerrain.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButtonValiderTerrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/correction.png"))); // NOI18N
        jButtonValiderTerrain.setText("Valider");
        jButtonValiderTerrain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonValiderTerrain.setMaximumSize(new java.awt.Dimension(110, 31));
        jButtonValiderTerrain.setMinimumSize(new java.awt.Dimension(110, 31));
        jButtonValiderTerrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderTerrainActionPerformed(evt);
            }
        });
        sectionTerain.add(jButtonValiderTerrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 110, -1));

        jSpinnerLargeurTerrain.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerLargeurTerrain.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionTerain.add(jSpinnerLargeurTerrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 110, 30));

        jSpinnerHauteurTerrain.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerHauteurTerrain.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionTerain.add(jSpinnerHauteurTerrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, 30));

        jSpinnerHauteurTerrain1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerHauteurTerrain1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionTerain.add(jSpinnerHauteurTerrain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, 30));

        jLabel49.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText(" Hauteur(y2):");
        sectionTerain.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 90, 20));

        jLabel50.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Largeur(x2):");
        sectionTerain.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 90, 20));

        jSpinnerLargeurTerrain1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerLargeurTerrain1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionTerain.add(jSpinnerLargeurTerrain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 110, 30));

        jPanel2.add(sectionTerain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 280, 200));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Générer terrain");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 20));

        sectionMaison.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel38.setText("Largeur:");
        sectionMaison.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 70, 20));

        jButtonValiderMaison.setBackground(new java.awt.Color(8, 126, 245));
        jButtonValiderMaison.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButtonValiderMaison.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/correction.png"))); // NOI18N
        jButtonValiderMaison.setText("Valider");
        jButtonValiderMaison.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonValiderMaison.setMaximumSize(new java.awt.Dimension(110, 31));
        jButtonValiderMaison.setMinimumSize(new java.awt.Dimension(110, 31));
        jButtonValiderMaison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderMaisonActionPerformed(evt);
            }
        });
        sectionMaison.add(jButtonValiderMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 110, -1));

        jLabel40.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel40.setText("Nbr de chambre:");
        jLabel40.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        sectionMaison.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 110, 20));

        jTextFieldNomMaison.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        sectionMaison.add(jTextFieldNomMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 260, 30));

        jLabel42.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel42.setText("Nom du villa:");
        sectionMaison.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 20));

        jLabel46.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel46.setText("Hauteur:");
        sectionMaison.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 70, 20));

        jLabel47.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Taille");
        sectionMaison.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 80, 20));

        jLabel39.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Marge");
        sectionMaison.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, 20));

        jLabel45.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel45.setText("Haut");
        sectionMaison.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 20));

        jLabel44.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel44.setText("Bas");
        sectionMaison.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 70, -1));

        jLabel43.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel43.setText("Gauche");
        jLabel43.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        sectionMaison.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 20));

        jLabel48.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel48.setText("Droite");
        jLabel48.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        sectionMaison.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 20));

        jSpinnerHautMaison.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerHautMaison.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionMaison.add(jSpinnerHautMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 30));

        jSpinnerBasMaison.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerBasMaison.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionMaison.add(jSpinnerBasMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, 30));

        jSpinnerNbrDeChambreMaison.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerNbrDeChambreMaison.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionMaison.add(jSpinnerNbrDeChambreMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 110, 30));

        jSpinnerGaucheMaison.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerGaucheMaison.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionMaison.add(jSpinnerGaucheMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 30));

        jSpinnerDroiteMaison.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerDroiteMaison.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionMaison.add(jSpinnerDroiteMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 110, 30));

        jSpinnerHauteurMaison.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerHauteurMaison.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionMaison.add(jSpinnerHauteurMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 110, 30));

        jSpinnerLargeurMaison.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerLargeurMaison.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionMaison.add(jSpinnerLargeurMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 110, 30));

        jPanel2.add(sectionMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 280, 330));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Générer Maison");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 90, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 300, 640));

        jPanel8.setBackground(new java.awt.Color(136, 157, 236));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(136, 157, 236));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 160, -1));

        jPanel10.setBackground(new java.awt.Color(136, 157, 236));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 160, -1));

        jPanel4.setBackground(new java.awt.Color(136, 157, 236));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 160, -1));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/shapes (1).png"))); // NOI18N
        jLabel22.setText("Formes");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 80, 30));

        jToolBar1.setBackground(new java.awt.Color(136, 157, 236));
        jToolBar1.setFloatable(true);
        jToolBar1.setRollover(true);

        sourisD.setBackground(new java.awt.Color(136, 157, 236));
        sourisD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cursor.png"))); // NOI18N
        sourisD.setFocusable(false);
        sourisD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sourisD.setMargin(new java.awt.Insets(2, 16, 3, 16));
        sourisD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sourisD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourisDActionPerformed(evt);
            }
        });
        jToolBar1.add(sourisD);

        texteD.setBackground(new java.awt.Color(136, 157, 236));
        texteD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/text.png"))); // NOI18N
        texteD.setFocusable(false);
        texteD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        texteD.setMargin(new java.awt.Insets(2, 16, 3, 16));
        texteD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        texteD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texteDActionPerformed(evt);
            }
        });
        jToolBar1.add(texteD);

        gaumeD.setBackground(new java.awt.Color(136, 157, 236));
        gaumeD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rubber.png"))); // NOI18N
        gaumeD.setFocusable(false);
        gaumeD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gaumeD.setMargin(new java.awt.Insets(2, 16, 3, 16));
        gaumeD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gaumeD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gaumeDActionPerformed(evt);
            }
        });
        jToolBar1.add(gaumeD);

        rectangleD.setBackground(new java.awt.Color(136, 157, 236));
        rectangleD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangle.png"))); // NOI18N
        rectangleD.setFocusable(false);
        rectangleD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rectangleD.setMargin(new java.awt.Insets(2, 16, 3, 16));
        rectangleD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rectangleD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectangleDActionPerformed(evt);
            }
        });
        jToolBar1.add(rectangleD);

        cercleD.setBackground(new java.awt.Color(136, 157, 236));
        cercleD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dry-clean.png"))); // NOI18N
        cercleD.setFocusable(false);
        cercleD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cercleD.setMargin(new java.awt.Insets(2, 16, 3, 16));
        cercleD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cercleD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cercleDActionPerformed(evt);
            }
        });
        jToolBar1.add(cercleD);

        ligneD.setBackground(new java.awt.Color(136, 157, 236));
        ligneD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/line.png"))); // NOI18N
        ligneD.setFocusable(false);
        ligneD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ligneD.setMargin(new java.awt.Insets(2, 16, 3, 16));
        ligneD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ligneD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ligneDActionPerformed(evt);
            }
        });
        jToolBar1.add(ligneD);

        jPanel8.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, 50));

        jToolBar3.setBackground(new java.awt.Color(136, 157, 236));
        jToolBar3.setRollover(true);

        styloPain.setBackground(new java.awt.Color(136, 157, 236));
        styloPain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/inclined-pencil.png"))); // NOI18N
        styloPain.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        styloPain.setMargin(new java.awt.Insets(2, 16, 3, 16));
        styloPain.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        styloPain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                styloPainActionPerformed(evt);
            }
        });
        jToolBar3.add(styloPain);

        stylo1Pain.setBackground(new java.awt.Color(136, 157, 236));
        stylo1Pain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fountain-pen-close-up.png"))); // NOI18N
        stylo1Pain.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stylo1Pain.setMargin(new java.awt.Insets(2, 16, 3, 16));
        stylo1Pain.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        stylo1Pain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stylo1PainActionPerformed(evt);
            }
        });
        jToolBar3.add(stylo1Pain);

        stylo2Pain.setBackground(new java.awt.Color(136, 157, 236));
        stylo2Pain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/brush-stroke.png"))); // NOI18N
        stylo2Pain.setFocusable(false);
        stylo2Pain.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stylo2Pain.setMargin(new java.awt.Insets(2, 16, 3, 16));
        stylo2Pain.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        stylo2Pain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stylo2PainActionPerformed(evt);
            }
        });
        jToolBar3.add(stylo2Pain);

        jPanel8.add(jToolBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 210, 50));

        jToolBar4.setBackground(new java.awt.Color(136, 157, 236));
        jToolBar4.setRollover(true);

        noireCou.setBackground(new java.awt.Color(136, 157, 236));
        noireCou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cube.png"))); // NOI18N
        noireCou.setFocusable(false);
        noireCou.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        noireCou.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        noireCou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noireCouActionPerformed(evt);
            }
        });
        jToolBar4.add(noireCou);

        blancCou.setBackground(new java.awt.Color(136, 157, 236));
        blancCou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cube (1).png"))); // NOI18N
        blancCou.setFocusable(false);
        blancCou.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        blancCou.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        blancCou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blancCouActionPerformed(evt);
            }
        });
        jToolBar4.add(blancCou);

        rougeCou.setBackground(new java.awt.Color(136, 157, 236));
        rougeCou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cube (2).png"))); // NOI18N
        rougeCou.setFocusable(false);
        rougeCou.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rougeCou.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rougeCou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rougeCouActionPerformed(evt);
            }
        });
        jToolBar4.add(rougeCou);

        bleueCou.setBackground(new java.awt.Color(136, 157, 236));
        bleueCou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cube (4).png"))); // NOI18N
        bleueCou.setFocusable(false);
        bleueCou.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bleueCou.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bleueCou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bleueCouActionPerformed(evt);
            }
        });
        jToolBar4.add(bleueCou);

        verteCou.setBackground(new java.awt.Color(136, 157, 236));
        verteCou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cube (9).png"))); // NOI18N
        verteCou.setFocusable(false);
        verteCou.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verteCou.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        verteCou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verteCouActionPerformed(evt);
            }
        });
        jToolBar4.add(verteCou);

        jauneCou.setBackground(new java.awt.Color(136, 157, 236));
        jauneCou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cube (6).png"))); // NOI18N
        jauneCou.setFocusable(false);
        jauneCou.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jauneCou.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jauneCou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jauneCouActionPerformed(evt);
            }
        });
        jToolBar4.add(jauneCou);

        orangeCou.setBackground(new java.awt.Color(136, 157, 236));
        orangeCou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cube (10).png"))); // NOI18N
        orangeCou.setFocusable(false);
        orangeCou.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        orangeCou.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        orangeCou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeCouActionPerformed(evt);
            }
        });
        jToolBar4.add(orangeCou);

        roseCou.setBackground(new java.awt.Color(136, 157, 236));
        roseCou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cube (8).png"))); // NOI18N
        roseCou.setFocusable(false);
        roseCou.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        roseCou.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        roseCou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roseCouActionPerformed(evt);
            }
        });
        jToolBar4.add(roseCou);

        jPanel8.add(jToolBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 30, 280, 50));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/color-palette (3).png"))); // NOI18N
        jLabel23.setText("Couleurs");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 80, 30));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/art.png"))); // NOI18N
        jLabel25.setText("Painceau");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 90, 30));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 1020, 80));

        jButtonEffacerTout.setBackground(new java.awt.Color(8, 126, 245));
        jButtonEffacerTout.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButtonEffacerTout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        jButtonEffacerTout.setText("Effacer tout");
        jButtonEffacerTout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEffacerTout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEffacerToutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEffacerTout, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 650, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Sur le nom d'utilisateur
    public void displayUsername() {
        
        jLabelNomUtilisateur.setText(getData.username);
        
    }
    


    private void jButtonEffacerToutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEffacerToutActionPerformed
        // TODO add your handling code here: 
        ZonneDessinContrainte jPanelZoneDessin = new ZonneDessinContrainte();
        jPanelZoneDessin.repaint();
    }//GEN-LAST:event_jButtonEffacerToutActionPerformed

    private void dashboardLogoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardLogoutBtnMouseClicked
      
        JOptionPane alert;
        // Afficher la boîte de dialogue de confirmation
        int response = JOptionPane.showConfirmDialog(null, "Êtes-vous sûr de vouloir déconnecter?", "Message de confirmation",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    
        // Si l'utilisateur clique sur "Oui"
        if (response == JOptionPane.YES_OPTION) {
              
            Dashboard.super.dispose();
            Connecter connect = new Connecter();
            connect.setVisible(true);
                        
        }else{
            
        }               
       
    }//GEN-LAST:event_dashboardLogoutBtnMouseClicked

    private void jButtonValiderTerrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderTerrainActionPerformed
        // TODO add your handling code here:
        JOptionPane alert;
        try {
            if (jTextFieldNomTerrain.getText().isEmpty()
                    || jSpinnerHauteurTerrain.getValue().equals(0)
                    || jSpinnerLargeurTerrain.getValue().equals(0)
                    || jSpinnerHauteurTerrain1.getValue().equals(0)
                    || jSpinnerLargeurTerrain1.getValue().equals(0)) {
                
                alert = new JOptionPane(JOptionPane.ERROR_MESSAGE);
                alert.showMessageDialog(null, "S'il vous plaît, vous devez d'abord complétez ces cases.");
                
            }else{
                
                // Insertion des données dans la base de données
                String sql = "INSERT INTO terrain (nomT, hauteurTy1, largeurTx1, hauteurTy2, largeurTx2)"
                        + "VALUES (?, ?, ?, ?, ?)";
                
                connect = (Connection) database.ConnectDb();
                
                prepare = connect.prepareStatement(sql);
                prepare.setString(1, jTextFieldNomTerrain.getText());
                prepare.setInt(2, (int) jSpinnerHauteurTerrain.getValue());
                prepare.setInt(3, (int) jSpinnerLargeurTerrain.getValue());
                prepare.setInt(4, (int) jSpinnerHauteurTerrain1.getValue());
                prepare.setInt(5, (int) jSpinnerLargeurTerrain1.getValue());
                
                prepare.executeUpdate();
                
                int hauteur = (int) jSpinnerHauteurTerrain.getValue();
                int largeur = (int) jSpinnerLargeurTerrain.getValue();
                
                getData.nomT = jTextFieldNomTerrain.getText();
                getData.hauteurTy1 = (Integer) jSpinnerHauteurTerrain.getValue();
                getData.largeurTx1 = (Integer) jSpinnerLargeurTerrain.getValue();
                getData.hauteurTy2 = (Integer) jSpinnerHauteurTerrain1.getValue();
                getData.largeurTx2 = (Integer) jSpinnerLargeurTerrain1.getValue();
                
                alert = new JOptionPane(JOptionPane.INFORMATION_MESSAGE);
                alert.showMessageDialog(null, "Réussi");
                
                
                jTextFieldNomTerrain.setText("");
                jSpinnerHauteurTerrain.setValue(0);
                jSpinnerLargeurTerrain.setValue(0);
                jSpinnerHauteurTerrain1.setValue(0);
                jSpinnerLargeurTerrain1.setValue(0);
            }
            
            
            } catch (Exception e) {
                e.printStackTrace();
            }
 
    }//GEN-LAST:event_jButtonValiderTerrainActionPerformed

    private void jButtonValiderMaisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderMaisonActionPerformed
        // TODO add your handling code here:
        
        // TODO add your handling code here:
        JOptionPane alert;
        try {
            if (jTextFieldNomMaison.getText().isEmpty()
                    || jSpinnerHautMaison.getValue().equals(0)
                    || jSpinnerBasMaison.getValue().equals(0)
                    || jSpinnerGaucheMaison.getValue().equals(0)
                    || jSpinnerDroiteMaison.getValue().equals(0)
                    || jSpinnerHauteurMaison.getValue().equals(0)
                    || jSpinnerLargeurMaison.getValue().equals(0)
                    || jSpinnerNbrDeChambreMaison.getValue().equals(0)) {
                
                alert = new JOptionPane(JOptionPane.ERROR_MESSAGE);
                alert.showMessageDialog(null, "S'il vous plaît, vous devez d'abord complétez ces cases.");
                
            }else{
                
                // Insertion des données dans la base de données
                String sql = "INSERT INTO maison (nomM, hautM, basM, gaucheM, droiteM, hauteurM, largeurM, nbrChambreM)"
                        + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                
                connect = (Connection) database.ConnectDb();
                
                prepare = connect.prepareStatement(sql);
                prepare.setString(1, jTextFieldNomMaison.getText());
                prepare.setInt(2, (int) jSpinnerHautMaison.getValue());
                prepare.setInt(3, (int) jSpinnerBasMaison.getValue());
                prepare.setInt(4, (int) jSpinnerGaucheMaison.getValue());
                prepare.setInt(5, (int) jSpinnerDroiteMaison.getValue());
                prepare.setInt(6, (int) jSpinnerHauteurMaison.getValue());
                prepare.setInt(7, (int) jSpinnerLargeurMaison.getValue());
                prepare.setInt(8, (int) jSpinnerNbrDeChambreMaison.getValue());
                
                prepare.executeUpdate();
                    
                       
                alert = new JOptionPane(JOptionPane.INFORMATION_MESSAGE);
                alert.showMessageDialog(null, "Réussi");
                
                jTextFieldNomMaison.setText("");
                jSpinnerHautMaison.setValue(0);
                jSpinnerBasMaison.setValue(0);
                jSpinnerGaucheMaison.setValue(0);
                jSpinnerDroiteMaison.setValue(0);
                jSpinnerHauteurMaison.setValue(0);
                jSpinnerLargeurMaison.setValue(0);
                jSpinnerNbrDeChambreMaison.setValue(0);
            }
            
            
            } catch (Exception e) {
                e.printStackTrace();
            }
        
        
    }//GEN-LAST:event_jButtonValiderMaisonActionPerformed

    private void jTextFieldNomTerrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomTerrainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomTerrainActionPerformed

    private void cercleDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cercleDActionPerformed
        // TODO add your handling code here:
        if(cercleD.isSelected()){
            sourisD.setSelected(false);
            texteD.setSelected(false);
            rectangleD.setSelected(false);
            ligneD.setSelected(false);
            gaumeD.setSelected(false);
        }else{
            
        }
        
    }//GEN-LAST:event_cercleDActionPerformed

    private void rectangleDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectangleDActionPerformed
        // TODO add your handling code here:
        if(rectangleD.isSelected()){
            sourisD.setSelected(false);
            texteD.setSelected(false);
            cercleD.setSelected(false);
            ligneD.setSelected(false);
            gaumeD.setSelected(false);
        }else{
            
        }
    }//GEN-LAST:event_rectangleDActionPerformed

    private void ligneDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ligneDActionPerformed
        // TODO add your handling code here:
        if(ligneD.isSelected()){
            sourisD.setSelected(false);
            texteD.setSelected(false);
            rectangleD.setSelected(false);
            cercleD.setSelected(false);
            gaumeD.setSelected(false);
        }else{
            
        }
    }//GEN-LAST:event_ligneDActionPerformed

    private void sourisDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourisDActionPerformed
        // TODO add your handling code here:
        if(sourisD.isSelected()){
            cercleD.setSelected(false);
            texteD.setSelected(false);
            rectangleD.setSelected(false);
            ligneD.setSelected(false);
            gaumeD.setSelected(false);
        }else{
            
        }
    }//GEN-LAST:event_sourisDActionPerformed

    private void texteDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texteDActionPerformed
        // TODO add your handling code here:
        if(texteD.isSelected()){
//            texteD.setCursor(Cursor.getPredefinedCursor(7));
            sourisD.setSelected(false);
            cercleD.setSelected(false);
            rectangleD.setSelected(false);
            ligneD.setSelected(false);
            gaumeD.setSelected(false);
        }else{
            
        }
    }//GEN-LAST:event_texteDActionPerformed

    private void gaumeDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaumeDActionPerformed
        // TODO add your handling code here:
        if(gaumeD.isSelected()){
            sourisD.setSelected(false);
            texteD.setSelected(false);
            rectangleD.setSelected(false);
            ligneD.setSelected(false);
            cercleD.setSelected(false);
        }else{
            
        }
    }//GEN-LAST:event_gaumeDActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void styloPainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_styloPainActionPerformed
        // TODO add your handling code here:
        if(styloPain.isSelected()){
            stylo1Pain.setSelected(false);
            stylo2Pain.setSelected(false);
        }else{
            
        }
    }//GEN-LAST:event_styloPainActionPerformed

    private void stylo1PainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stylo1PainActionPerformed
        // TODO add your handling code here:
        if(stylo1Pain.isSelected()){
            styloPain.setSelected(false);
            stylo2Pain.setSelected(false);
        }else{
            
        }
    }//GEN-LAST:event_stylo1PainActionPerformed

    private void stylo2PainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stylo2PainActionPerformed
        // TODO add your handling code here:
        if(stylo2Pain.isSelected()){
            stylo1Pain.setSelected(false);
            styloPain.setSelected(false);
        }else{
            
        }
    }//GEN-LAST:event_stylo2PainActionPerformed

    private void noireCouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noireCouActionPerformed
        // TODO add your handling code here:
        if(noireCou.isSelected()){
            blancCou.setSelected(false);
            rougeCou.setSelected(false);
            bleueCou.setSelected(false);
            verteCou.setSelected(false);
            jauneCou.setSelected(false);
            orangeCou.setSelected(false);
            roseCou.setSelected(false);
        }else{
            
        }
    }//GEN-LAST:event_noireCouActionPerformed

    private void blancCouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blancCouActionPerformed
        // TODO add your handling code here:
        if(blancCou.isSelected()){
            noireCou.setSelected(false);
            rougeCou.setSelected(false);
            bleueCou.setSelected(false);
            verteCou.setSelected(false);
            jauneCou.setSelected(false);
            orangeCou.setSelected(false);
            roseCou.setSelected(false);
        }else{
            
        }
    }//GEN-LAST:event_blancCouActionPerformed

    private void rougeCouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rougeCouActionPerformed
        // TODO add your handling code here:
        if(rougeCou.isSelected()){
            blancCou.setSelected(false);
            noireCou.setSelected(false);
            bleueCou.setSelected(false);
            verteCou.setSelected(false);
            jauneCou.setSelected(false);
            orangeCou.setSelected(false);
            roseCou.setSelected(false);
        }else{
            
        }
    }//GEN-LAST:event_rougeCouActionPerformed

    private void bleueCouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bleueCouActionPerformed
        // TODO add your handling code here:
        if(bleueCou.isSelected()){
            blancCou.setSelected(false);
            rougeCou.setSelected(false);
            noireCou.setSelected(false);
            verteCou.setSelected(false);
            jauneCou.setSelected(false);
            orangeCou.setSelected(false);
            roseCou.setSelected(false);
        }else{
            
        }
    }//GEN-LAST:event_bleueCouActionPerformed

    private void verteCouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verteCouActionPerformed
        // TODO add your handling code here:
        if(verteCou.isSelected()){
            blancCou.setSelected(false);
            rougeCou.setSelected(false);
            bleueCou.setSelected(false);
            noireCou.setSelected(false);
            jauneCou.setSelected(false);
            orangeCou.setSelected(false);
            roseCou.setSelected(false);
        }else{
            
        }
    }//GEN-LAST:event_verteCouActionPerformed

    private void jauneCouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jauneCouActionPerformed
        // TODO add your handling code here:
        if(jauneCou.isSelected()){
            blancCou.setSelected(false);
            rougeCou.setSelected(false);
            bleueCou.setSelected(false);
            verteCou.setSelected(false);
            noireCou.setSelected(false);
            orangeCou.setSelected(false);
            roseCou.setSelected(false);
        }else{
            
        }
    }//GEN-LAST:event_jauneCouActionPerformed

    private void orangeCouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeCouActionPerformed
        // TODO add your handling code here:
        if(orangeCou.isSelected()){
            blancCou.setSelected(false);
            rougeCou.setSelected(false);
            bleueCou.setSelected(false);
            verteCou.setSelected(false);
            jauneCou.setSelected(false);
            noireCou.setSelected(false);
            roseCou.setSelected(false);
        }else{
            
        }
    }//GEN-LAST:event_orangeCouActionPerformed

    private void roseCouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roseCouActionPerformed
        // TODO add your handling code here:
        if(roseCou.isSelected()){
            blancCou.setSelected(false);
            rougeCou.setSelected(false);
            bleueCou.setSelected(false);
            verteCou.setSelected(false);
            jauneCou.setSelected(false);
            orangeCou.setSelected(false);
            noireCou.setSelected(false);
        }else{
            
        }
    }//GEN-LAST:event_roseCouActionPerformed

    private void enregistrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enregistrerMouseClicked
        // TODO add your handling code here:
        int SV;
        
        SV = JOptionPane.showConfirmDialog(null, "Voule-vous enregistrez votre travail?", 
                "Sauvegarder", JOptionPane.YES_NO_OPTION);
        
        if(SV==0){
            BufferedImage im = new BufferedImage(this.getWidth(), this.getHeight(), BufferedImage.TYPE_INT_ARGB);
//            this.ajouterMonZoneDessinContrainte(ZonneDessinContrainte jPanelZoneDessin(im.getGraphics()));
            
            try {
                JFileChooser fileChooser = new JFileChooser();
                int result = fileChooser.showSaveDialog(null);
                if(result==JFileChooser.APPROVE_OPTION){
                    File file = fileChooser.getSelectedFile();
                    ImageIO.write(im, "PNG", file);
                }else{
                    
                }
            } catch (IOException ex) {
//                Logger.getLogger(ZonneDessinContrainte.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_enregistrerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
        
        // Exécuter l'application sur le thread de dispatch des événements
//        SwingUtilities.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                // Créer une instance de la fenêtre et la rendre visible
//                new Dashboard().setVisible(true);
//            }
//        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton blancCou;
    private javax.swing.JToggleButton bleueCou;
    private javax.swing.JToggleButton cercleD;
    private javax.swing.JLabel dashboardLogoutBtn;
    private javax.swing.JLabel enregistrer;
    private javax.swing.JLabel enregistrerSous;
    private javax.swing.JToggleButton gaumeD;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonEffacerTout;
    private javax.swing.JButton jButtonValiderMaison;
    public javax.swing.JButton jButtonValiderTerrain;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNomUtilisateur;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSpinner jSpinnerBasMaison;
    private javax.swing.JSpinner jSpinnerDroiteMaison;
    private javax.swing.JSpinner jSpinnerGaucheMaison;
    private javax.swing.JSpinner jSpinnerHautMaison;
    private javax.swing.JSpinner jSpinnerHauteurMaison;
    private javax.swing.JSpinner jSpinnerHauteurTerrain;
    private javax.swing.JSpinner jSpinnerHauteurTerrain1;
    private javax.swing.JSpinner jSpinnerLargeurMaison;
    private javax.swing.JSpinner jSpinnerLargeurTerrain;
    private javax.swing.JSpinner jSpinnerLargeurTerrain1;
    private javax.swing.JSpinner jSpinnerNbrDeChambreMaison;
    private javax.swing.JTextField jTextFieldNomMaison;
    private javax.swing.JTextField jTextFieldNomTerrain;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToggleButton jauneCou;
    private javax.swing.JToggleButton ligneD;
    private javax.swing.JToggleButton noireCou;
    private javax.swing.JLabel nouveau;
    private javax.swing.JToggleButton orangeCou;
    private javax.swing.JLabel ouvrir;
    private javax.swing.JToggleButton rectangleD;
    private javax.swing.JToggleButton roseCou;
    private javax.swing.JToggleButton rougeCou;
    private javax.swing.JPanel sectionMaison;
    private javax.swing.JPanel sectionTerain;
    private javax.swing.JToggleButton sourisD;
    private javax.swing.JToggleButton stylo1Pain;
    private javax.swing.JToggleButton stylo2Pain;
    private javax.swing.JToggleButton styloPain;
    private javax.swing.JToggleButton texteD;
    private javax.swing.JToggleButton verteCou;
    // End of variables declaration//GEN-END:variables
}
