/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Controller.DashboardController;
import Controller.ZoneDessinController;
import java.util.*;
import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import miaproject.database;

/**
 *
 * @author KADAFI Ben
 */
public class Dashboard extends javax.swing.JFrame {
    
    
    private Connection connect;
    
    private PreparedStatement prepare;
    
    private Statement statement;
    
    private ResultSet result;
    
    Graphics g;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
                
        displayUsername();
        
//        g = jPanelZoneDessin.getGraphics();
//        jPanelZoneDessin.paintComponents(g);
//        DashboardController dash = new DashboardController(jPanelZoneDessin);
//        jPanelZoneDessin.addMouseListener(new ZoneDessinController (dash));
//        dash.start();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelNomUtilisateur = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dashboardLogoutBtn = new javax.swing.JLabel();
        sectionTerain = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTextFieldNomTerrain = new javax.swing.JTextField();
        jButtonValiderTerrain = new javax.swing.JButton();
        jSpinnerLargeurTerrain = new javax.swing.JSpinner();
        jSpinnerHauteurTerrain = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        sectionMaison = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jButtonValiderMaison = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jTextFieldNomMaison = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jSpinnerHautMaison = new javax.swing.JSpinner();
        jSpinnerBasMaison = new javax.swing.JSpinner();
        jSpinnerNbrDeChambreMaison = new javax.swing.JSpinner();
        jSpinnerGaucheMaison = new javax.swing.JSpinner();
        jSpinnerDroiteMaison = new javax.swing.JSpinner();
        jSpinnerHauteurMaison = new javax.swing.JSpinner();
        jSpinnerLargeurMaison = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabelColorPicker = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        rectangleD = new javax.swing.JLabel();
        cercleD = new javax.swing.JLabel();
        ligneD = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelZoneDessin = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonEffacerTout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user (2).png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 50, 70));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/folder_1.png"))); // NOI18N
        jLabel7.setText("Ouvrir");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 100, 70));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/new-document.png"))); // NOI18N
        jLabel8.setText("Nouveau");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 100, 70));

        jLabel24.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/diskette (1).png"))); // NOI18N
        jLabel24.setText("Enregistrer");
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 100, 70));

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/save.png"))); // NOI18N
        jLabel16.setText("Enregistrer sous");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 150, 70));

        jLabelNomUtilisateur.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabelNomUtilisateur.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomUtilisateur.setText("User name");
        jPanel1.add(jLabelNomUtilisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(1047, 6, 140, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 70));

        jPanel2.setBackground(new java.awt.Color(136, 157, 236));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardLogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        dashboardLogoutBtn.setText(" Déconnexion");
        dashboardLogoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardLogoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardLogoutBtnMouseClicked(evt);
            }
        });
        jPanel2.add(dashboardLogoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 110, 30));

        sectionTerain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Largeur:");
        sectionTerain.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 70, 20));

        jLabel37.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText(" Hauteur:");
        sectionTerain.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 70, 20));

        jLabel41.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel41.setText("Nom du terrain:");
        sectionTerain.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 20));

        jTextFieldNomTerrain.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextFieldNomTerrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomTerrainActionPerformed(evt);
            }
        });
        sectionTerain.add(jTextFieldNomTerrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 260, 30));

        jButtonValiderTerrain.setBackground(new java.awt.Color(8, 126, 245));
        jButtonValiderTerrain.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButtonValiderTerrain.setForeground(new java.awt.Color(255, 255, 255));
        jButtonValiderTerrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.png"))); // NOI18N
        jButtonValiderTerrain.setText("Valider");
        jButtonValiderTerrain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonValiderTerrain.setMaximumSize(new java.awt.Dimension(110, 31));
        jButtonValiderTerrain.setMinimumSize(new java.awt.Dimension(110, 31));
        jButtonValiderTerrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderTerrainActionPerformed(evt);
            }
        });
        sectionTerain.add(jButtonValiderTerrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 110, -1));

        jSpinnerLargeurTerrain.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerLargeurTerrain.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionTerain.add(jSpinnerLargeurTerrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 110, 30));

        jSpinnerHauteurTerrain.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerHauteurTerrain.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionTerain.add(jSpinnerHauteurTerrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, 30));

        jPanel2.add(sectionTerain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 280, 150));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Générer terrain");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 20));

        sectionMaison.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel38.setText("Largeur:");
        sectionMaison.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 70, 20));

        jButtonValiderMaison.setBackground(new java.awt.Color(8, 126, 245));
        jButtonValiderMaison.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButtonValiderMaison.setForeground(new java.awt.Color(255, 255, 255));
        jButtonValiderMaison.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.png"))); // NOI18N
        jButtonValiderMaison.setText("Valider");
        jButtonValiderMaison.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonValiderMaison.setMaximumSize(new java.awt.Dimension(110, 31));
        jButtonValiderMaison.setMinimumSize(new java.awt.Dimension(110, 31));
        jButtonValiderMaison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderMaisonActionPerformed(evt);
            }
        });
        sectionMaison.add(jButtonValiderMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 110, -1));

        jLabel40.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel40.setText("Nbr de chambre:");
        jLabel40.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        sectionMaison.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 110, 20));

        jTextFieldNomMaison.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        sectionMaison.add(jTextFieldNomMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 260, 30));

        jLabel42.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel42.setText("Nom du villa:");
        sectionMaison.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 20));

        jLabel46.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel46.setText("Hauteur:");
        sectionMaison.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 70, 20));

        jLabel47.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Taille");
        sectionMaison.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 80, 20));

        jLabel39.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Marge");
        sectionMaison.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, 20));

        jLabel45.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel45.setText("Haut");
        sectionMaison.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 20));

        jLabel44.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel44.setText("Bas");
        sectionMaison.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 70, 20));

        jLabel43.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel43.setText("Gauche");
        jLabel43.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        sectionMaison.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 20));

        jLabel48.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel48.setText("Droite");
        jLabel48.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        sectionMaison.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 110, 20));

        jSpinnerHautMaison.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerHautMaison.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionMaison.add(jSpinnerHautMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 30));

        jSpinnerBasMaison.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerBasMaison.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionMaison.add(jSpinnerBasMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, 30));

        jSpinnerNbrDeChambreMaison.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerNbrDeChambreMaison.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionMaison.add(jSpinnerNbrDeChambreMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 110, 30));

        jSpinnerGaucheMaison.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerGaucheMaison.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionMaison.add(jSpinnerGaucheMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 110, 30));

        jSpinnerDroiteMaison.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerDroiteMaison.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionMaison.add(jSpinnerDroiteMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, 30));

        jSpinnerHauteurMaison.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerHauteurMaison.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionMaison.add(jSpinnerHauteurMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 110, 30));

        jSpinnerLargeurMaison.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jSpinnerLargeurMaison.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        sectionMaison.add(jSpinnerLargeurMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 110, 30));

        jPanel2.add(sectionMaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 280, 360));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Générer Maison");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 90, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 300, 620));

        jPanel8.setBackground(new java.awt.Color(136, 157, 236));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(136, 157, 236));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 160, -1));

        jPanel10.setBackground(new java.awt.Color(136, 157, 236));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelColorPicker.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabelColorPicker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/art.png"))); // NOI18N
        jLabelColorPicker.setText("    Couleur");
        jLabelColorPicker.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelColorPicker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelColorPickerMouseClicked(evt);
            }
        });
        jPanel10.add(jLabelColorPicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 100, 60));

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 160, -1));

        jPanel4.setBackground(new java.awt.Color(136, 157, 236));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 160, -1));

        jPanel11.setBackground(new java.awt.Color(136, 157, 236));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cursor.png"))); // NOI18N
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 60));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/text.png"))); // NOI18N
        jPanel11.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 60));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/inclined-pencil.png"))); // NOI18N
        jPanel11.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 60));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/opened-door-aperture.png"))); // NOI18N
        jPanel11.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, 60));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sink.png"))); // NOI18N
        jPanel11.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, 60));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rubber.png"))); // NOI18N
        jPanel11.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, 60));

        rectangleD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangle.png"))); // NOI18N
        jPanel11.add(rectangleD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, 60));

        cercleD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dry-clean.png"))); // NOI18N
        jPanel11.add(cercleD, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, 60));

        ligneD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/line.png"))); // NOI18N
        jPanel11.add(ligneD, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, 60));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/window.png"))); // NOI18N
        jPanel11.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, 60));

        jPanel8.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 60));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/resize.png"))); // NOI18N
        jLabel22.setText("     Rédimentionner");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 140, 60));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 1020, 60));

        jPanelZoneDessin.setBackground(new java.awt.Color(255, 255, 255));
        jPanelZoneDessin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jPanelZoneDessin);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 1000, 480));

        jButton5.setBackground(new java.awt.Color(8, 126, 245));
        jButton5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.png"))); // NOI18N
        jButton5.setText("Ajouter");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setMaximumSize(new java.awt.Dimension(110, 31));
        jButton5.setMinimumSize(new java.awt.Dimension(110, 31));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, 130, -1));

        jButton3.setBackground(new java.awt.Color(8, 126, 245));
        jButton3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit-button.png"))); // NOI18N
        jButton3.setText("Modifier");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 640, 140, -1));

        jButtonEffacerTout.setBackground(new java.awt.Color(8, 126, 245));
        jButtonEffacerTout.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButtonEffacerTout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEffacerTout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        jButtonEffacerTout.setText("Effacer tout");
        jButtonEffacerTout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEffacerTout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEffacerToutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEffacerTout, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 640, 130, -1));

        jButton1.setBackground(new java.awt.Color(8, 126, 245));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh-page-option.png"))); // NOI18N
        jButton1.setText("Actualiser");
        jButton1.setToolTipText("");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 640, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Sur le nom d'utilisateur
    public void displayUsername() {
        
        jLabelNomUtilisateur.setText(getData.username);
        
    }
    


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonEffacerToutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEffacerToutActionPerformed
        // TODO add your handling code here:
        jPanelZoneDessin.repaint();
    }//GEN-LAST:event_jButtonEffacerToutActionPerformed

    private void dashboardLogoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardLogoutBtnMouseClicked
      
        JOptionPane alert;
        // Afficher la boîte de dialogue de confirmation
        int response = JOptionPane.showConfirmDialog(null, "Êtes-vous sûr de vouloir déconnecter?", "Message de confirmation",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    
        // Si l'utilisateur clique sur "Oui"
        if (response == JOptionPane.YES_OPTION) {
              
            Dashboard.super.dispose();
            Connecter connect = new Connecter();
            connect.setVisible(true);
                        
        }else{
            
        }               
       
    }//GEN-LAST:event_dashboardLogoutBtnMouseClicked

    private void jButtonValiderTerrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderTerrainActionPerformed
        // TODO add your handling code here:
        JOptionPane alert;
        try {
            if (jTextFieldNomTerrain.getText().isEmpty()
                    || jSpinnerHauteurTerrain.getValue().equals(0)
                    || jSpinnerLargeurTerrain.getValue().equals(0)) {
                
                alert = new JOptionPane(JOptionPane.ERROR_MESSAGE);
                alert.showMessageDialog(null, "S'il vous plaît, vous devez d'abord complétez ces cases.");
                
            }else{
                
                // Insertion des données dans la base de données
                String sql = "INSERT INTO terrain (nomT, hauteurT, largeurT)"
                        + "VALUES (?, ?, ?)";
                
                connect = (Connection) database.ConnectDb();
                
                prepare = connect.prepareStatement(sql);
                prepare.setString(1, jTextFieldNomTerrain.getText());
                prepare.setInt(2, (int) jSpinnerHauteurTerrain.getValue());
                prepare.setInt(3, (int) jSpinnerLargeurTerrain.getValue());
                
                prepare.executeUpdate();
                
                int hauteur = (int) jSpinnerHauteurTerrain.getValue();
                int largeur = (int) jSpinnerLargeurTerrain.getValue();
                      
                alert = new JOptionPane(JOptionPane.INFORMATION_MESSAGE);
                alert.showMessageDialog(null, "Réussi");
                
//                g.drawRect(50, 50, largeur, hauteur);
                
                jTextFieldNomTerrain.setText("");
                jSpinnerHauteurTerrain.setValue(0);
                jSpinnerLargeurTerrain.setValue(0);
            }
            
            
            } catch (Exception e) {
                e.printStackTrace();
            }
 
    }//GEN-LAST:event_jButtonValiderTerrainActionPerformed

    private void jButtonValiderMaisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderMaisonActionPerformed
        // TODO add your handling code here:
        
        // TODO add your handling code here:
        JOptionPane alert;
        try {
            if (jTextFieldNomMaison.getText().isEmpty()
                    || jSpinnerHautMaison.getValue().equals(0)
                    || jSpinnerBasMaison.getValue().equals(0)
                    || jSpinnerGaucheMaison.getValue().equals(0)
                    || jSpinnerDroiteMaison.getValue().equals(0)
                    || jSpinnerHauteurMaison.getValue().equals(0)
                    || jSpinnerLargeurMaison.getValue().equals(0)
                    || jSpinnerNbrDeChambreMaison.getValue().equals(0)) {
                
                alert = new JOptionPane(JOptionPane.ERROR_MESSAGE);
                alert.showMessageDialog(null, "S'il vous plaît, vous devez d'abord complétez ces cases.");
                
            }else{
                
                // Insertion des données dans la base de données
                String sql = "INSERT INTO maison (nomM, hautM, basM, gaucheM, droiteM, hauteurM, largeurM, nbrChambreM)"
                        + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                
                connect = (Connection) database.ConnectDb();
                
                prepare = connect.prepareStatement(sql);
                prepare.setString(1, jTextFieldNomMaison.getText());
                prepare.setInt(2, (int) jSpinnerHautMaison.getValue());
                prepare.setInt(3, (int) jSpinnerBasMaison.getValue());
                prepare.setInt(4, (int) jSpinnerGaucheMaison.getValue());
                prepare.setInt(5, (int) jSpinnerDroiteMaison.getValue());
                prepare.setInt(6, (int) jSpinnerHauteurMaison.getValue());
                prepare.setInt(7, (int) jSpinnerLargeurMaison.getValue());
                prepare.setInt(8, (int) jSpinnerNbrDeChambreMaison.getValue());
                
                prepare.executeUpdate();
                    
                       
                alert = new JOptionPane(JOptionPane.INFORMATION_MESSAGE);
                alert.showMessageDialog(null, "Réussi");
                
                jTextFieldNomMaison.setText("");
                jSpinnerHautMaison.setValue(0);
                jSpinnerBasMaison.setValue(0);
                jSpinnerGaucheMaison.setValue(0);
                jSpinnerDroiteMaison.setValue(0);
                jSpinnerHauteurMaison.setValue(0);
                jSpinnerLargeurMaison.setValue(0);
                jSpinnerNbrDeChambreMaison.setValue(0);
            }
            
            
            } catch (Exception e) {
                e.printStackTrace();
            }
        
        
    }//GEN-LAST:event_jButtonValiderMaisonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextFieldNomTerrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomTerrainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomTerrainActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabelColorPickerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelColorPickerMouseClicked
        // TODO add your handling code here
        ColorPicker colPick = new ColorPicker();
        colPick.setVisible(true);
        
//       colPick.setVisible(false);
    }//GEN-LAST:event_jLabelColorPickerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Dashboard().setVisible(true);
//            }
//        });
        
        // Exécuter l'application sur le thread de dispatch des événements
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                // Créer une instance de la fenêtre et la rendre visible
                new Dashboard().setVisible(true);
            }
        });
        
//        displayUsername();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cercleD;
    private javax.swing.JLabel dashboardLogoutBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonEffacerTout;
    private javax.swing.JButton jButtonValiderMaison;
    private javax.swing.JButton jButtonValiderTerrain;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelColorPicker;
    private javax.swing.JLabel jLabelNomUtilisateur;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelZoneDessin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerBasMaison;
    private javax.swing.JSpinner jSpinnerDroiteMaison;
    private javax.swing.JSpinner jSpinnerGaucheMaison;
    private javax.swing.JSpinner jSpinnerHautMaison;
    private javax.swing.JSpinner jSpinnerHauteurMaison;
    private javax.swing.JSpinner jSpinnerHauteurTerrain;
    private javax.swing.JSpinner jSpinnerLargeurMaison;
    private javax.swing.JSpinner jSpinnerLargeurTerrain;
    private javax.swing.JSpinner jSpinnerNbrDeChambreMaison;
    private javax.swing.JTextField jTextFieldNomMaison;
    private javax.swing.JTextField jTextFieldNomTerrain;
    private javax.swing.JLabel ligneD;
    private javax.swing.JLabel rectangleD;
    private javax.swing.JPanel sectionMaison;
    private javax.swing.JPanel sectionTerain;
    // End of variables declaration//GEN-END:variables
}
